# fly.toml app configuration file generated for go-spordlfy-hidden-violet-3026 on 2024-04-04T17:22:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-spordlfy'
primary_region = 'ams'





[env]
  DB_URL = 'main.db'
  PORT = '4200'
  SPOTIFY_CLIENT_ID = '1ec6cb1a181e47368d762606d2851929'
  BASEURL='https://go-spordlfy.fly.dev'

[http_service]
  internal_port = 4200
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
